// Mock RSS data for Refinery — matches brief's 10 categories
window.REFINERY_DATA = {
  inbox: [
    { id: "i-unread", icon: "inbox",    label: "All Unread", count: 3022, current: true, hot: true },
    { id: "i-today",  icon: "spark",    label: "Today",      count: 184 },
    { id: "i-kept",   icon: "bookmark", label: "Kept",       count: 21 },
    { id: "i-read",   icon: "check",    label: "Read later", count: 6 },
  ],
  // The 10 brief-specified categories, each with a tailored monoline glyph
  categories: [
    { id: "news",      label: "News",      icon: "cat-news",     count: 412, hot: true },
    { id: "ai",        label: "AI",        icon: "cat-ai",       count: 217, hot: true },
    { id: "finance",   label: "Finance",   icon: "cat-finance",  count: 520, hot: true },
    { id: "learning",  label: "Learning",  icon: "cat-learning", count: 38 },
    { id: "tech",      label: "Tech",      icon: "cat-tech",     count: 144, hot: true },
    { id: "watches",   label: "Watches",   icon: "cat-watches",  count: 9 },
    { id: "youtube",   label: "YouTube",   icon: "cat-youtube",  count: 27 },
    { id: "reddit",    label: "Reddit",    icon: "cat-reddit",   count: 257, hot: true },
    { id: "email",     label: "Email",     icon: "cat-email",    count: 18 },
    { id: "duplicate", label: "Duplicate", icon: "cat-dup",      count: 0 },
  ],
  sources: [
    { id: "fool",  fav: "F", color: "c4", url: "fool.com",        count: 312 },
    { id: "rd",    fav: "R", color: "c4", url: "reddit.com/r/prog", count: 254 },
    { id: "hn",    fav: "Y", color: "c4", url: "ycombinator.com", count: 91 },
    { id: "verge", fav: "V", color: "c3", url: "theverge.com",     count: 38 },
    { id: "stra",  fav: "S", color: "c5", url: "stratechery.com", count: 4 },
  ],
  articles: [
    {
      id: "a1",
      source: "Hacker News", sourceFav: "Y", sourceColor: "c4",
      category: "Tech", time: "12 MIN",
      title: "Two kernel-level netfilter exploits in eight days — maintainers ask for a freeze",
      deck: "A second root-path vulnerability lands in the conntrack module within a week. The combined exposure window now spans most of the 6.10 LTS series.",
      snippet: "An out-of-bounds write in the netfilter conntrack module gives unprivileged local users a clean path to root on every distribution shipping the 6.10 series.",
      hero: true,
      progress: 0,
      unread: true,
      tag: "Security",
    },
    {
      id: "a2",
      source: "Stratechery", sourceFav: "S", sourceColor: "c5",
      category: "Analysis", time: "1 HR",
      title: "The aggregation tax, ten years on",
      deck: "Re-reading Aggregation Theory after a decade of regulatory pushback, AI search, and the slow unwind of the open web.",
      snippet: "When I first wrote about aggregators, the assumption was that consumer demand would be the steady state. The last two years have proven this assumption was always conditional.",
      hero: true,
      progress: 42,
      unread: true,
      kept: true,
      tag: "Essay",
    },
    {
      id: "a3",
      source: "Fox Sports", sourceFav: "F", sourceColor: "c4",
      category: "News", time: "2 HR",
      title: "Minor league pitcher throws an unbelievable celebration after a soft line drive",
      snippet: "There are the celebrations you think about ahead of time, and the spur-of-the-moment ones. This pitcher invented a third kind.",
      progress: 100,
      unread: false,
    },
    {
      id: "a4",
      source: "r/programming", sourceFav: "R", sourceColor: "c4",
      category: "Tech", time: "3 HR",
      title: "Bun ported to Rust in six days",
      deck: "A small team rewrites the JavaScript runtime's hot path in Rust over a long weekend. Benchmarks attached.",
      snippet: "We started Tuesday morning and by Sunday night the test suite was passing. The porting was largely mechanical; the interesting work was in the GC bridge.",
      progress: 0,
      unread: true,
      tag: "Discussion",
    },
    {
      id: "a5",
      source: "The Verge", sourceFav: "V", sourceColor: "c3",
      category: "Tech", time: "4 HR",
      title: "AI air-traffic system reports fewer flight delays in pilot regions",
      deck: "Six months into the FAA's machine-learning rollout, on-time arrivals are up — but controllers say the metric hides the real cost.",
      snippet: "The agency reported a 14% reduction in arrival delays at twelve test airports. Union representatives note that controllers are working with reduced staffing margins.",
      hero: true,
      progress: 0,
      unread: true,
    },
    {
      id: "a6",
      source: "Motley Fool", sourceFav: "F", sourceColor: "c4",
      category: "Finance", time: "5 HR",
      title: "Five data-broker opt-out myths that leave retirees exposed",
      snippet: "Have you already tried removing your personal information from data broker sites? Maybe you Googled your name and didn't like what you found.",
      progress: 0,
      unread: true,
    },
    {
      id: "a7",
      source: "One Useful Thing", sourceFav: "O", sourceColor: "c5",
      category: "AI", time: "YESTERDAY",
      title: "On the slow web, and the comfort of a small inbox",
      deck: "An argument for reading less, but reading better. The case for boredom, marginalia, and rereading the same essays for years.",
      snippet: "I've kept the same fifteen RSS feeds since 2018. They are not the most important feeds in the world. They are mine.",
      hero: true,
      progress: 78,
      unread: false,
      kept: true,
    },
    {
      id: "a8",
      source: "MIT Tech Review", sourceFav: "M", sourceColor: "c3",
      category: "AI", time: "YESTERDAY",
      title: "The model that refused to scale past 400B",
      deck: "Inside an attempt to push a 70B-parameter architecture forward — and the unexpected reasons it stopped improving.",
      snippet: "By the time training reached the third checkpoint, the loss had stopped decreasing. The team's first instinct was a data issue.",
      progress: 0,
      unread: true,
      kept: true,
    },
    {
      id: "a9",
      source: "Working Title", sourceFav: "W", sourceColor: "c2",
      category: "Essay", time: "2 DAYS",
      title: "Notebooks, again",
      deck: "Why every productivity tool eventually becomes a notebook, and why the notebook is the part that actually matters.",
      snippet: "Every team I've watched build a tool for their own work has eventually arrived at the same shape: a list of pages, a search bar, and a place to paste things.",
      progress: 0,
      unread: false,
      kept: true,
    },
  ],
  articleBody: [
    "Around 03:00 UTC last Tuesday, a maintainer of the Linux kernel's netfilter subsystem pushed a quiet patch with the unremarkable subject line conntrack: fix oob write on resize. Within forty minutes, three independent researchers had identified that the same flaw provided an unprivileged path to ring 0 on every mainline release shipped since June.",
    "Two days earlier, the kernel had absorbed Pinned Frag — a different but mechanically similar bug in the same module. The combined window of exposure now stretches across most of the 6.10 series, including the long-term-support point releases that ship in nearly every enterprise distribution.",
    "What's striking is not the bugs themselves — netfilter has been a fertile source of root exploits for fifteen years — but the velocity. Two production-grade root paths in eight calendar days suggests something has changed in the part of the kernel that handles network state, and it has changed faster than the review process can absorb.",
  ]
};
